### ISSUE TITLE
Action (master) does not work anymore

### ISSUE THREAD

**Issue by Guite** [peaceiris/actions-hugo#135]
**Describe the bug**
Builds using the "master" version of this action are broken.

Error message:

`##[error]File not found: '/home/runner/work/_actions/peaceiris/actions-hugo/master/lib/index.js'`

**To Reproduce**

Use the following definition in a workflow:

```
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@master
      with:
        hugo-version: 'latest'
        extended: true
```
