### ISSUE TITLE
Code Highlighting doesn't work - Azure Static Web Apps

### ISSUE THREAD

**Issue by lucabol** [peaceiris/actions-hugo#336]
Compiling my Hugo based blog on Netlify produces code highlighting for my posts. Using this extension doesn't. I have set both to compile with the same hugo version 0.64.0. I have tried with Hugo Extended as well.

Compare the two sites:
[Netlify](https://www.lucabol.com/posts/2019-12-06-status-of-csharp-8-functional-features-with-a-comparison-to-haskell/)
[Azure](https://lively-forest-02f09a703.azurestaticapps.net/posts/2019-12-06-status-of-csharp-8-functional-features-with-a-comparison-to-haskell/)

## Your YAML file

https://github.com/lucabol/MyBlog

**Comment by peaceiris** [comment]
I have deployed your site to the GitHub Pages. The code Highlighting looks good.

Your problem seems to be caused by the `Azure/static-web-apps-deploy` action. I recommend you to open another issue at the repository.

https://peaceiris.github.io/MyBlog/posts/2019-12-06-status-of-csharp-8-functional-features-with-a-comparison-to-haskell/

```yaml
name: GitHub Pages

on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.64.0"
          extended: true

      - run: hugo

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
```

<img width="906" alt="Screen Shot 2020-05-21 at 22 21 15" src="https://user-images.githubusercontent.com/30958501/82563138-743ea280-9bb1-11ea-93f5-15008bc2755d.png">
