### ISSUE TITLE
Build issue with docsy-example repo

### ISSUE THREAD

**Issue by capsulecorplab** [peaceiris/actions-hugo#340]
## Describe the bug

Adding the [example workflow](https://github.com/peaceiris/actions-hugo#%EF%B8%8F-create-your-workflow) in forked [docsy-example](https://github.com/google/docsy-example) repo results in the following error:

https://github.com/capsulecorplab/docsy-example/runs/700468489?check_suite_focus=true#step:4:5 

## To Reproduce

1. Fork https://github.com/google/docsy-example.git
2. Create `.github/workflows/` directory in forked repo
3. Create and add `deploy.yml` file with [example workflow](https://github.com/peaceiris/actions-hugo#%EF%B8%8F-create-your-workflow) to `.github/workflows/` directory
4. Commit changes
5. See build log in GitHub Actions

## Expected behavior

A successful build.

## Your YAML file

https://github.com/capsulecorplab/docsy-example/commit/ba3919d13e0d7b3db1581ffb6250d176994d0c79

**Comment by peaceiris** [comment]
Turn on `extended: true` to process SCSS. (Hugo extended version!)

**Comment by peaceiris** [comment]
BTW, GitHub is down now. Maybe you will get the following issues.

- [Github token results in Permission denied to github-actions · Issue #319 · peaceiris/actions-gh-pages](https://github.com/peaceiris/actions-gh-pages/issues/319)
- [repository not found · Issue #254 · actions/checkout](https://github.com/actions/checkout/issues/254)

**Comment by capsulecorplab** [comment]
> BTW, GitHub is down now. Maybe you will get the following issues.
> 
> * [Github token results in Permission denied to github-actions · Issue #319 · peaceiris/actions-gh-pages](https://github.com/peaceiris/actions-gh-pages/issues/319)
> * [repository not found · Issue #254 · actions/checkout](https://github.com/actions/checkout/issues/254)

Thanks! I'll probably tackle these once the SCSS processing gets resolved.

**Comment by capsulecorplab** [comment]
> Turn on `extended: true` to process SCSS. (Hugo extended version!)

Just pushed a commit with `extended: true`. Still running into same issue https://github.com/capsulecorplab/docsy-example/runs/700653318?check_suite_focus=true#step:4:5

**Comment by peaceiris** [comment]
I also failed to build your project locally. Your problem is related to the docsy-example or the docsy theme. Please ask them about this issue. Or go to the Hugo forum.

**Comment by peaceiris** [comment]
> https://github.com/google/docsy-example/issues/60#issuecomment-632903155
>
> I got it. You need to install the dependencies: autoprefixer and postcss-cli. Please try the following workflow.

```yaml
name: github pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive  # Fetch the Docsy theme
          fetch-depth: 0         # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.71.1'
          extended: true

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - run: npm ci
      - run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
```
