### ISSUE TITLE
does this support git submodule

### ISSUE THREAD

**Issue by vinurs** [peaceiris/actions-hugo#42]
my hugo theme is included as a submodule, but when use this it seems that it doesn't clone the submodule, so the generated files doesn't work as expected

**Comment by peaceiris** [comment]
Your problem is unrelated to this action. But I answer for you.

Try the following. It will work well.

```yaml
- uses: actions/checkout@master
  with:
    submodules: true
```
checkout/action.yml - actions/checkout: https://github.com/actions/checkout/blob/94d077c24971944d312dd9197c1bdfba62b39878/action.yml#L13
