### ISSUE TITLE
Invalid JSON Response Body from brew.sh

### ISSUE THREAD

**Issue by brandoningli** [peaceiris/actions-hugo#461]
## Describe the bug

Action fails due to an invalid json response body from brew.sh

`Error: Action failed with error invalid json response body at https://formulae.brew.sh/api/formula/hugo.json reason: Unexpected token < in JSON at position 1`

## To Reproduce

1. Trigger the action

## Expected behavior

Hugo setup succeeds

## YAML

```yaml
- name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
          hugo-version: 'latest'
```

## Additional Details

This might be a brew.sh temporary error.
