### ISSUE TITLE
Unable to build docsy sample with the default action

### ISSUE THREAD

**Issue by hajekj** [peaceiris/actions-hugo#463]
The documentation specifies [following action](https://github.com/peaceiris/actions-hugo#%EF%B8%8F-workflow-for-autoprefixer-and-postcss-cli) to build the [docsy-example](https://github.com/google/docsy-example) repo. However when using it, I end up with following: `Error: Error building site: TOCSS: failed to transform "scss/main.scss" (text/x-scss): SCSS processing failed: file "stdin", line 6, col 1: File to import not found or unreadable: ../vendor/bootstrap/scss/bootstrap.`

The issue appears to be that deeper submodules aren't fetched for some reason. I ended up with adding following action:
```
      - name: Fetch Submodules # Above action doesn't seem to do it properly for some reason
        run: git submodule update --init --recursive
```
which clones the submodules properly. If this is an issue in the clone action, I can create the issue there.

Related to https://github.com/google/docsy/issues/279

**Comment by peaceiris** [comment]
Did you set the `submodules` to `recursive` really? See the instruction again carefully.

```yaml
      - uses: actions/checkout@v2
        with:
          submodules: recursive  # Fetch the Docsy theme ❗️ ʕ◔ϖ◔ʔ
          fetch-depth: 0
```
