### ISSUE TITLE
Impossible to pass env variable to `hugo-version` option

### ISSUE THREAD

**Issue by martignoni** [peaceiris/actions-hugo#467]
## Describe the bug

With following setup in workflow:
```
…
env:
    HUGO_RELEASE: '0.76.5'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: ${HUGO_RELEASE}
          extended: true
…
```
I'm getting this error: `Error: Action failed with error Object prototype may only be an Object or null: undefined`. Replacing the var with the explicit version number, i.e. '0.76.5' works correctly.

## To Reproduce

1. Define an env var HUGO_RELEASE in workflow
2. Use the var $HUGO_RELEASE in `with: hugo-version:` 
3. Commit change

## Expected behavior

Env var HUGO_RELEASE should be expanded without error.

## Screenshots

<img width="897" alt="workflow-error" src="https://user-images.githubusercontent.com/421392/99116072-b80be500-25f3-11eb-8f35-900aa3b0353e.png">

## Your YAML file

- A link to your repository: https://github.com/moodlebox/moodlebox.net/
- A link to your YAML file: https://github.com/moodlebox/moodlebox.net/blob/master/.github/workflows/deploy.yml

## Additional context

Nothing.
