### ISSUE TITLE
Chinese filename git lastmod will change

### ISSUE THREAD

**Issue by lingsamuel** [peaceiris/actions-hugo#496]
## Describe the bug

I enabled GitInfo and set `fetch-depth: 0` in github actions.

Files with ascii filename works well. But files with Chinese (or non-ascii? not sure) always generate "now" as lastmod (just like GitInfo disabled).

I am not sure if it's a actions-hugo bug or hugo bug. But the lastmod works pretty well locally, so I guess it's the actions probelm?

## To Reproduce

1. Create post with Chinese filename, such as `中文文件名.md`
2. Push to the remote repo, the actions run and deploy
3. Trigger the action without modifying the file above
3. See the lastmod changes (in sitemap.xml or else)

## Expected behavior

The lastmod should be stable.

## Screenshots

![image](https://user-images.githubusercontent.com/14567045/110205568-afe1f900-7eb3-11eb-97cc-8b45a772217a.png)

This is my last deploy.  lastmod of the Chinese filename post (the encoded url one) changed to "now".

## Your YAML file

<details>

```yaml
name: github pages

on:
  watch:
    types: started
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        # run: hugo -t beautifulhugo --minify
        # run: hugo --minify --buildDrafts -t beautifulhugo --ignoreCache
        run: hugo --minify -t beautifulhugo --ignoreCache
      
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: master
          #github_token: ${{ secrets.GITHUB_TOKEN }}
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          publish_dir: ./public
          external_repository: lingsamuel/lingsamuel.github.io
```

</details>

**Comment by lingsamuel** [comment]
I found some potential related issue:
https://github.com/gohugoio/hugo/issues/3071
https://github.com/gohugoio/hugo/issues/6803


I tried this:

```
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: disable quotePath
        run: git config --global core.quotePath false # HERE

      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
```

It works well now.
