### ISSUE TITLE
Subfolder modules - Add path where to run the workflow in

### ISSUE THREAD

**Issue by davidsneighbour** [peaceiris/actions-hugo#509]
## Is your feature request related to a problem? Please describe.

I have a mono repository that contains multiple modules for Hugo. I want to run a website for every single module (subfolder). 

## Describe the solution you'd like

```
on:
  push:
    tags:
      - 'some-module/v*'
...
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          path: "some-module"
          hugo-version: 'latest'
          extended: true
```

I would like to propose a with-parameter that makes this action to run inside of a subfolder instead of the main folder of the repository. 

## Describe alternatives you've considered

none. the only alternative would be to move each single module into it's own repository. 

## Additional context

for instance see https://github.com/dnb-hugo/shortcodes and the youtube subfolder with the .github workflow setup.

**Comment by peaceiris** [comment]
This action just installs Hugo into a GitHub Actions runner. I do not understand the purpose of the parameter. Could you tell me more details?

I guess you want the `strategy.matrix`. cf. https://github.com/alex-shpak/hugo-book/pull/289/files

**Comment by mifriis** [comment]
Hi @davidsneighbour 

We used working-directory as a way to specify that the action should run on a specific subfolder:
```
      - name: Build
        working-directory: ./handbook
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./handbook/public
```

in this case the handbook is in the "handbook" folder in the root of the repository
