### ISSUE TITLE
Manage Node version by .nvmrc

### ISSUE THREAD

**Issue by peaceiris** [peaceiris/actions-hugo#55]
```yaml
- name: Read .nvmrc
  run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
  id: nvm

- name: Setup Node
  uses: actions/setup-node@v1
  with:
    node-version: "${{ steps.nvm.outputs.NVMRC }}"
```

> https://github.com/actions/setup-node/issues/32#issuecomment-525791142

- [Development tools for GitHub Actions - GitHub Help](https://help.github.com/en/articles/development-tools-for-github-actions#set-an-output-parameter-set-output)
