### ISSUE TITLE
support: Node.js 16 actions are deprecated

### ISSUE THREAD

**Issue by yusufmalikul** [peaceiris/actions-hugo#647]
### Checklist

- [X] I am using the latest version of this action.
- [X] I have read the latest README and followed the instructions.
- [X] I have read the latest GitHub Actions official documentation and learned the basic spec and concepts.

### Describe your question

I use `peaceiris/actions-hugo@v2` but get deprecated version warning.

### Relevant links

```markdown
Public repository:
YAML config:
YAML workflow:
```

### Relevant log output

>Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: peaceiris/actions-hugo@v2. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

### Additional context.

```
- name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.101.0'
```

**Comment by yusufmalikul** [comment]
@undergroundwires the current workaround is to use the commit hash:
```
uses: peaceiris/actions-hugo@16361eb4acea8698b220b76c0d4e84e1fd22c61d
```

**Comment by Shaoting-Feng** [comment]
Got this error
`Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: peaceiris/actions-hugo@16361eb4acea8698b220b76c0d4e84e1fd22c61d. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.`

**Comment by chipzoller** [comment]
This was addressed in #641 but @peaceiris needs to cut a release.

**Comment by elibroftw** [comment]
I forked the project, updated the dependencies, and added the dist.
```
uses: elibroftw/actions-hugo@8c27d714d00dc4a9c40c3c9a91a1176f000b6ab9
```

**Comment by peaceiris** [comment]
Thanks all!

Could you please try v3.0.0?

```yaml
      - uses: peaceiris/actions-hugo@v3.0.0
        with:
          hugo-version: '0.124.1'
```
