### ISSUE TITLE
proposal: hugo >0.137.0: offer possibility to use 'withdeploy' release

### ISSUE THREAD

**Issue by deining** [peaceiris/actions-hugo#658]
### Checklist

- [X] I am using the latest version of this action.
- [X] I have read the latest README and followed the instructions.
- [X] I have read the latest GitHub Actions official documentation and learned the basic spec and concepts.

### Describe your proposal

As of hugo version, the deploy subcommand is not part of hugo's extended version any more.
If you want to make use of hugo deploy, you have to download and install a release with 'withdeploy' in the archive filename. See https://github.com/gohugoio/hugo/pull/12995 for further details.

### Describe the solution you'd like

As far as I can see, currently it is not possible to make use of the 'withdeploy` version inside of a workflow definition.
Therefore I would like to propose to introduce a new boolean `withdeploy` that allows to make use of the hugo verison taht includes the `deploy` feature:

```
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.119.0'
          extended: true
          withdeploy: true  # <-- request to add this new option
```

### Describe alternatives you've considered

None

### Additional context

None

**Comment by peaceiris** [comment]
Nice catch! ʕ◔ϖ◔ʔ

- https://github.com/peaceiris/actions-hugo/pull/659 is in progress

**Comment by jbouse** [comment]
On consideration that the existing #659 doesn't check or enforce is that `withdeploy` is implicitly `extended` as it is `extended_withdeploy` not just `withdeploy`.

I didn't see anything that would catch the following invalid config:
```
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.137.0'
          # extended: false # Default is actually false
          withdeploy: true  # <-- request to add this new option
```
